name: flutter_signature_view
description: The signature plugin serve place to paint your signature and export it to many differences type to store.
version: 1.1.0
author: AnhNDT<anhndt.vng@gmail.com>
homepage: https://github.com/kzjn10/Flutter_SignatureWidget/tree/master/flutter_signature_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
